# P.S. in production this file should never be pushed on Git or be leaked,
# but since this is my own project, and this is just a portfolio project,
# it's annoying me to see this file not commited, so I commit it :).
# Thanks for understanding.
DB_URL=localhost
DB_PORT=5432
DB_NAME=task_tracker_db
DB_USERNAME=task_tracker_api_owner
DB_PASSWORD=qwerty_12345

ASYMMETRIC_JWT_ISSUER=http://localhost:8081
ASYMMETRIC_JWT_EXPIRATION=3600000
ASYMMETRIC_JWT_ALGORITHM=RSA
RSA_PRIVATE_KEY_PATH=/Users/artyom_aroyan/Software/Java/.keys/private_key.pem
RSA_PUBLIC_KEY_PATH=/Users/artyom_aroyan/Software/Java/.keys/public_key.pem

ARGON2_MEMORY=65536
ARGON2_ITERATIONS=3
ARGON2_PARALLELISM=2
ARGON2_HASH_LENGTH=64
ARGON2_SALT_LENGTH=64
ARGON2_PEPPER=jUsCmDlJ6ImfnlJVOGj0c5Xku4BHDeZ2EXjXLQV64RTbaunaLR5s0h6lSRDqeKesH4QXkYyHeFKW8nNrI2+1Bg==