spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:/postgresql://${DB_URL}:${DB_PORT}:/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      show-sql: true

  security:
    jwt:
      issuer: ${ASYMMETRIC_JWT_ISSUER}
      algorithm: ${ASYMMETRIC_JWT_KEY_ALGORITHM}
      expiration: ${ASYMMETRIC_JWT_KEY_EXPIRATION}