spring:
  application:
    name: user-service
  profiles:
    active: local

  r2dbc:
    url: r2dbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schemas: users
    default-schema: users
    baseline-on-migrate: true
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver

  security:
    jwt:
      issuer: ${ASYMMETRIC_JWT_ISSUER}
      expiration: ${ASYMMETRIC_JWT_EXPIRATION}
      algorithm: ${ASYMMETRIC_JWT_ALGORITHM}
      rsa-private-key-path: ${RSA_PRIVATE_KEY_PATH}
      rsa-public-key-path: ${RSA_PUBLIC_KEY_PATH}
    argon2:
      memory: ${ARGON2_MEMORY}
      iterations: ${ARGON2_ITERATIONS}
      parallelism: ${ARGON2_PARALLELISM}
      hash-length: ${ARGON2_HASH_LENGTH}
      salt-length: ${ARGON2_SALT_LENGTH}
      pepper: ${ARGON2_PEPPER}

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

logging:
  level:
    web: info
    sql: info
    org:
      tasktracker:
        demo:
          userservice:
            application: debug
            infrastructure: debug
            security: debug
            presentation: debug
      flywaydb: info
      springframework:
        data:
          r2dbc:
            core: info
          _: info
        r2dbc: info
    io:
      r2dbc:
        postgresql: info