# task-service's application.yml
spring:
  application:
    name: task-service
  profiles:
    active: local

  r2dbc:
    url: r2dbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schemas: tasks
    default-schema: tasks
    baseline-on-migrate: true
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

server:
  port: 8082

logging:
  level:
    web: info
    sql: info
    org:
      tasktracker:
        demo:
          taskservice:
            application: info
            infrastructure: info
            security: info
            presentation: info
      flywaydb: info
      springframework:
        security:
          web: info
          core: info
          access: info
          authentication: info
          authorization: info
        _: info
        web:
          reactive: info
          _: info
    reactor:
      Netty:
        http:
          client: info
        data:
          r2dbc:
            core: info
          _: info
        r2dbc: info
    io:
      r2dbc:
        PostgreSQL: info