# P.S. in production this file should never be pushed on Git or be leaked,
# but since this is my own project, and this is just a portfolio project,
# it's annoying me to see this file not commited, so I commit it :).
# Thanks for understanding.
DB_URL=localhost
DB_PORT=5432
DB_NAME=task_tracker_db
DB_USERNAME=task_tracker_api_owner
DB_PASSWORD=qwerty_12345