spring:
  application:
    name: task-service
  profiles:
    active: local

  r2dbc:
    url: r2dbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    name: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schemas: tasks
    default-schema: tasks
    baseline-on-migrate: true
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true