plugins {
    id 'java'
    id 'maven-publish'
}

group = 'org.tasktracker.demo'
version = '1.0-SNAPSHOT'

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId 'org.tasktracker.demo'
            artifactId 'common-service'
            version '1.0-SNAPSHOT'
        }
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation("org.springframework:spring-context:7.0.1")
    compileOnly "org.projectlombok:lombok:1.18.42"
    annotationProcessor "org.projectlombok:lombok:1.18.42"
    implementation("io.projectreactor:reactor-core:3.7.12")
}

test {
    useJUnitPlatform()
}